# Generated by Django 5.0.1 on 2024-04-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aal', models.IntegerField()),
                ('aapl', models.IntegerField()),
                ('amzn', models.IntegerField()),
                ('bac', models.IntegerField()),
                ('dal', models.IntegerField()),
                ('hmc', models.IntegerField()),
                ('jnj', models.IntegerField()),
                ('jpm', models.IntegerField()),
                ('lly', models.IntegerField()),
                ('luv', models.IntegerField()),
                ('msft', models.IntegerField()),
                ('tm', models.IntegerField()),
                ('tsla', models.IntegerField()),
                ('unh', models.IntegerField()),
                ('v', models.IntegerField()),
                ('totalValue', models.FloatField()),
            ],
        ),
    ]
